// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChapter = "chapters"

// Chapter mapped from table <chapters>
type Chapter struct {
	ID         string `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	CourseID   string `gorm:"column:course_id;not null" json:"course_id"`
	Title      string `gorm:"column:title;not null" json:"title"`
	OrderIndex int32  `gorm:"column:order_index;default:1" json:"order_index"`
}

// TableName Chapter's table name
func (*Chapter) TableName() string {
	return TableNameChapter
}
