// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourse = "courses"

// Course mapped from table <courses>
type Course struct {
	ID          string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	TeacherID   string    `gorm:"column:teacher_id;not null" json:"teacher_id"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Description string    `gorm:"column:description" json:"description"`
	Price       float64   `gorm:"column:price" json:"price"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
}

// TableName Course's table name
func (*Course) TableName() string {
	return TableNameCourse
}
