// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCourseCategory = "course_categories"

// CourseCategory mapped from table <course_categories>
type CourseCategory struct {
	CourseID   string `gorm:"column:course_id;primaryKey" json:"course_id"`
	CategoryID string `gorm:"column:category_id;primaryKey" json:"category_id"`
}

// TableName CourseCategory's table name
func (*CourseCategory) TableName() string {
	return TableNameCourseCategory
}
