// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEnrollment = "enrollments"

// Enrollment mapped from table <enrollments>
type Enrollment struct {
	ID         string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	CourseID   string    `gorm:"column:course_id;not null" json:"course_id"`
	EnrolledAt time.Time `gorm:"column:enrolled_at;default:now()" json:"enrolled_at"`
	Progress   float64   `gorm:"column:progress" json:"progress"`
}

// TableName Enrollment's table name
func (*Enrollment) TableName() string {
	return TableNameEnrollment
}
