// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLesson = "lessons"

// Lesson mapped from table <lessons>
type Lesson struct {
	ID         string `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	CourseID   string `gorm:"column:course_id;not null" json:"course_id"`
	ChapterID  string `gorm:"column:chapter_id;not null" json:"chapter_id"`
	Title      string `gorm:"column:title;not null" json:"title"`
	Content    string `gorm:"column:content" json:"content"`
	OrderIndex int32  `gorm:"column:order_index;default:1" json:"order_index"`
}

// TableName Lesson's table name
func (*Lesson) TableName() string {
	return TableNameLesson
}
