// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           string    `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Email        string    `gorm:"column:email;not null" json:"email"`
	PasswordHash string    `gorm:"column:password_hash;not null" json:"password_hash,omitempty"`
	Role         string    `gorm:"column:role;not null;default:student" json:"role"`
	CreatedAt    time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
